name: Build and deploy on push
on:
  push:
    branches:
      - master
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master Branch
      uses: actions/checkout@master
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TUMBLR_CONSUMER_KEY: ${{ secrets.TUMBLR_CONSUMER_KEY }}
        BUILD_SCRIPT: npm install && npm run-script build
        COMMIT_EMAIL: hello@crock.dev
        COMMIT_NAME: Alex Crocker
        BRANCH: gh-pages
        FOLDER: public
